image: docker:20.10.14

services:
  - docker:20.10.14-dind

variables:
  DOCKER_IMAGE: "qhuong1008/mori-backend"
  DOCKER_USER: "qhuong1008"
  DOCKER_PASSWORD: "Huong560045@"
  REMOTE_SERVER: "hcmute@103.130.211.150"
  REMOTE_PORT: 10038
  SSH_SERVER_IP: "103.130.211.150"
  MORI_SSH_PRIVATE_KEY: $MORI_SSH_PRIVATE_KEY
  ID_RSA: "~/.ssh/id_rsa"

stages:
  - access-remote-server
  - deploy
  - build

build:
  stage: build
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker build -t backend .
    - docker tag backend "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"

access-remote-server:
  stage: access-remote-server
  script:
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n      SendEnv CI_*  \n" > ~/.ssh/config
    - echo -n  "$MORI_SSH_PRIVATE_KEY"  > ~/.ssh/id_rsa
    - chmod og= "$ID_RSA"
    - apk update && apk add openssh-client
    - ssh -i "$ID_RSA" -o StrictHostKeyChecking=no -p 10038 hcmute@103.130.211.150

deploy:
  stage: deploy
  environment: production
  script:
    - cd project/MoriApp_20110141_20110335/mori-app-deploy/
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d

  only:
    - main
