image: docker:20.10.14

services:
  - docker:20.10.14-dind

variables:
  DOCKER_IMAGE: "qhuong1008/mori-backend"
  DOCKER_USER: "qhuong1008"
  DOCKER_PASSWORD: "Huong560045@"
  REMOTE_SERVER: "hcmute@103.130.211.150"
  REMOTE_PORT: 10038

stages:
  - deploy
  - build

build:
  stage: build
  script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker build -t backend .
    - docker tag backend "$DOCKER_IMAGE"
    - docker push "$DOCKER_IMAGE"

deploy:
  stage: deploy
  environment: production
  script:
    - echo "$MORI_SSH_PRIVATE_KEY"
    - echo "$MORI_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - cd project/MoriApp_20110141_20110335/mori-app-deploy/
    - docker-compose down
    - docker-compose pull
    - docker-compose up -d

  only:
    - main
