name: CI - Backend
on:
  push:
    branches:
      - lien
jobs:
  ci-backend:
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v3
      - name: Login docker
        run: docker login -u nguyenlien -p C!gtnH7yWyM24uX
      - name: Build backend
        run: docker build -t nguyenlien/mori-backend .
      - name: Push image
        run: docker push nguyenlien/mori-backend
